# Generated by Django 2.1.15 on 2020-04-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TEST',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Test_Table',
            },
        ),
    ]
