# Generated by Django 2.1.15 on 2020-04-03 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_name_english', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'm_company',
            },
        ),
        migrations.CreateModel(
            name='Current_Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_status_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'm_current_status',
            },
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=255)),
                ('dep_parent_id', models.IntegerField()),
            ],
            options={
                'db_table': 'm_dept',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('employe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employe_name', models.CharField(max_length=255)),
                ('employe_code', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('dep_id', models.IntegerField()),
                ('base_on', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'm_employe',
            },
        ),
    ]
