# Generated by Django 2.1.15 on 2020-04-03 02:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_company_current_status_dept_employe'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='current_status',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dept',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employe',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
