# Generated by Django 2.1.15 on 2020-04-08 07:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0004_auto_20200403_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'm_user_info',
            },
        ),
    ]
