# Generated by Django 2.1.15 on 2020-04-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0005_user_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='username_name',
            new_name='username',
        ),
    ]
