"""
Django settings for iplan_django project.

Generated by 'django-admin startproject' using Django 2.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4bxbtri#6strz5^tes$jfplc&pmd+4&!cr58idfy8onh!6&$^x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    #注册session
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'quote.apps.QuoteConfig',
    'rest_framework_swagger',
    "rest_framework",

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 注册session

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'iplan_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'iplan_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
##连接mysql 数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'YZDQUOTE',
        'USER':'root', ##root是超级用户
        'PASSWORD':'root',
        'HOST':'39.100.237.11',
        'PORT':'3306',
    },
}
#django.db.utils.OperationalError: (1665,
# 数据库端的问题
# SET GLOBAL binlog_format = 'ROW';
# show variables like 'binlog_format';

# #连接 sql server   pip install django-pyodbc-azure  需要修改 django的 版本
# DATABASES = {
#   'default': {
#     'ENGINE': 'sql_server.pyodbc',			        # odbc连接固定写法
#     'NAME': 'YZDQUOTE',				            # 自定义数据库连接名
#     'USER': 'iplan',					                # 数据库连接账户
#     'PASSWORD': '1234qwerasdfzxcv!',				        # 数据库连接密码
#     'HOST': '117.50.82.37',				            # 数据库服务地址
#     'PORT': '1433',					                # 数据库连接端口
#     'OPTIONS':{
#         'driver':'SQL Server Native Client 11.0',	# ODBC连接应用驱动
#         'MARS_Connection': True,
#     }
#   }
# }

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
